<?php
header("Cache-Control: no-cache");
error_reporting(0);
if(isset($_GET['userName'])){
	$username = $_GET['userName'];
	$url = 'https://twitter.com/'.$username;
	echo '<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss" xmlns:twitter="http://api.twitter.com" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <atom:link href="http://twitrss.me/twitter_user_to_rss/?user='.$username.'" rel="self" type="application/rss+xml" /> 
    <title>Twitter '.$username.' </title>
    <link>https://twitter.com/'.$username.'</link>
    <description>Twitter feed for: '.$username.'. Generated by piagno.ch</description>
    <language>en-us</language>
    <ttl>40</ttl>
    <!--<image>
        <url>https://pbs.twimg.com/profile_images/789093479305637888/eebPBItP_400x400.jpg</url>
    </image>-->';
	$file = file_get_contents($url);
	$doc = new DOMDocument();
	$doc->loadHTML($file);
	$items = $doc->getElementById('stream-items-id');
	foreach($items->childNodes as $item){
		if($item->tagName == 'li'){
			$wrapper = ($item->childNodes)[1];
			foreach($wrapper->childNodes as $wrapperItem){
				if($wrapperItem->tagName == 'div'){
					$header = ($wrapperItem->childNodes)[1];
					$date = ($header->childNodes)[3];
					$content = ($wrapperItem->childNodes)[3];
					if($header != null){
						echo '<item>
	  <title>'.substr($content->textContent,0,50).'</title>
	  <!--<dc:creator>(@osm)</dc:creator>-->
	  <description><![CDATA['.$content->textContent.']]></description>
	  <pubDate>'.$date->textContent.'</pubDate>
      <!--<guid>https://twitter.com/openstreetmap/status/1064542205107417088</guid>
      <link>https://twitter.com/openstreetmap/status/1064542205107417088</link>-->
      <twitter:source/>
      <twitter:place/></item>';
					}
				}
			}
		}
	}
	echo '
  </channel>
</rss>  ';
}